version: '3'
services:
  jira:
    build: ../..
    ports:
     - "8080:8080"
    depends_on:
      - jira_pg_db
  jira_pg_db:
    image: postgres
    environment:
    - POSTGRES_USER=jira
    - POSTGRES_PASSWORD=mysecretpassword
