version: '3'
services:
  web:
    build: ../..
    ports:
     - "8080:8080"
    environment:
    - DB_VENDOR=MYSQL
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=password
    - MYSQL_PORT_3306_TCP_ADDR=db
    depends_on:
      - db
  db:
    image: mysql
    environment:
    - MYSQL_DATABASE=keycloak
    - MYSQL_ROOT_PASSWORD=mysecretpassword
    - MYSQL_USER=keycloak
    - MYSQL_PASSWORD=password
